extends: eslint:recommended
parserOptions:
  ecmaVersion: 6
  sourceType: module

env:
  es6: true
  node: true

rules:
  no-unused-vars:
    - 2
    - args: none
      varsIgnorePattern: debug

  semi:
    - 2
    - 'always'
